# Generated by Django 5.2 on 2025-04-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matchperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('all', 'All Products'), ('featured', 'Featured'), ('sale', 'On Sale'), ('new', 'New Arrivals'), ('bestseller', 'Bestsellers')], default='all', max_length=20)),
            ],
        ),
    ]
